app/models/activity.rb, app/models/availability.rb, db/migrate/20200825104446_create_activities.rb, db/schema.rb
Ajout de la colonne "content dans la table "activities"
=> content in activities added

db/migrate/20200825105000_create_availabilities.rb, db/schema.rb
Ajout de activity_id dans la table availabilities
=> activityID added to availabilities

.gitignore, Gemfile, Gemfile.lock, app/models/activity.rb, app/models/user.rb, config/environments/development.rb, config/storage.yml, db/migrate/20200825152737_create_active_storage_tables.active_storage.rb, db/schema.rb
Ajout de cloudinary, vous avez besoin de bundle car ajout de gem
=> seed-aventurier

app/controllers/reviews_controller.rb, app/controllers/searches_controller.rb, app/controllers/trips_controller.rb, app/models/activity.rb, app/models/search.rb, app/models/trip.rb, config/routes.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/controllers/searches_controller_test.rb, test/controllers/trips_controller_test.rb
=> routes and controllers added

Gemfile.lock, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, db/schema.rb
Ajout de la video + footer fini et render sur toutes les pages normaly !
=> finish-homepage

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
J'ai modifié le logo du footer et mis en place les images !!
=> footer-homepage

.gitignore, app/controllers/trips_controller.rb, app/javascript/packs/application.js, app/views/trips/edit.html.erb, db/seeds.rb
La search amène à une carte avec picto des activités slectionnées
=> Auto complete

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss
modif du footer et taille des images homepages
=> some-modif

app/controllers/trips_controller.rb, app/javascript/components/search.js, app/javascript/packs/application.js, app/javascript/packs/autocomplete.js, app/javascript/packs/mapbox.js, app/views/layouts/application.html.erb, app/views/searches/new.html.erb, app/views/trips/edit.html.erb
=> turbolinks done

app/javascript/packs/application.js
=> porblem solved

app/assets/stylesheets/pages/sign-in.scss, app/views/devise/sessions/new.html.erb
=> devise to do

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/sign-in.scss, app/views/devise/sessions/new.html.erb
le form de devise ressemble à qq chose
=> form devise done

app/views/layouts/application.html.erb
Poblème de log out:       ActionController::InvalidAuthenticityToken in Devise::SessionsController#destroy
réglé de la manière suivante : dans layout
application.html.erb
ADDed         <%= csrf_meta_tag %>
<meta name="csrf-token" content="I+nZnT$#Twefelfjiself" />
=> authenticity token

app/assets/stylesheets/components/_avatar.scss, app/views/searches/new.html.erb
object-fit: cover    sur l'avatar
=> avatar redimensionnné

Gemfile, Gemfile.lock, app/controllers/pages_controller.rb, app/views/pages/charte.html.erb, app/views/pages/contact.html.erb, app/views/pages/team.html.erb, app/views/searches/new.html.erb, app/views/shared/_home_navbar.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, package.json
Modif des navbars:
Ajout des routes vers les pages nos valeurs, notre equipe et contact
Ajout typeform dans la page contact, ne fonctionne pas, probleme de serveur de la part de typeform, avoir dans les jours qui suivent !
=> joboftoday2

app/controllers/trips_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/trips/show.html.erb
La carte de la show marche et affiche un itinéraire
=> map is working on trip#show

Gemfile, Gemfile.lock, app/views/searches/new.html.erb, app/views/trips/show.html.erb, config/boot.rb
=> navbar added to show

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/select2.scss, app/controllers/pages_controller.rb, app/javascript/plugins/init_select2.js, app/views/shared/_home_navbar.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
les liens dans la nav fonctionnent
et le select2 doit fonctionner en prod
=> pages statics ok select2

app/javascript/packs/flatpickr.js
date de la search en céfran et dans l'ordre J M A
problème initial : altInput: true (bloquait les options)
=> flacpickr en cefran

app/javascript/packs/flatpickr.js
format "mercredi 12 septembre 2020"
=> date ok sur search

app/controllers/trips_controller.rb, app/javascript/plugins/init_mapbox.js
ajout de l'option overview=full dans mapbox (précision de l'itinéraire)
=> itineraire ok

app/controllers/trips_controller.rb, app/views/trips/show.html.erb
la user story est complete, la show marche
=> user story done

app/controllers/selected_activities_controller.rb, app/views/selected_activities/_form.html.erb, app/views/selected_activities/create.js.erb, app/views/selected_activities/update.js.erb, app/views/trips/edit.html.erb
Ajax implémenté sur l'édit de trips
=> show is working
